### ISSUE TITLE
Compatibility for Tinker's Tool Levelling

### ISSUE THREAD

**Issue by reddvilzz** [Invadermonky/Timber-Tree_Felling#1]
Hi, I'm using 

Timber! - 1.1.0
Tinker's Construct - 2.13.0.183
[Liketechniks Tinker Tweaks](https://github.com/liketechnik/Liketechnik-s-Tinker-Tweaks) - 1.0.0

And when I use the tree chopping to chop all of the woods, I won't get tool xp from it, but when I just normally using it to chop one wood at the time the xp still counts.

**Comment by Invadermonky** [comment]
Unfortunately, it is unlikely that I will add this functionality. To actually add leveling experience to Timber would require a specific call to the Tinker's Leveling code to correctly apply values based on the number of blocks broken. Additionally, since Tinker's Construct already includes its own tree harvesting mechanic through the Broad Axe, adding experience to a secondary harvesting mechanic seems like an exploit.

That being said, I am changing the way a few interactions work in the next update of Timber, including the way damage is applied to tools (which is how experience is applied through Tinker's Leveling). This change might add the functionality you are looking for, but if it does not, it is unlikely that i will add explicit support.

**Comment by Invadermonky** [comment]
Unfortunately, it is unlikely that I will add this functionality. To actually add leveling experience to Timber would require a specific call to the Tinker's Leveling code to correctly apply values based on the number of blocks broken. Additionally, since Tinker's Construct already includes its own tree harvesting mechanic through the Broad Axe, adding experience to a secondary harvesting mechanic seems like an exploit.

That being said, I am changing the way a few interactions work in the next update of Timber, including the way damage is applied to tools (which is how experience is applied through Tinker's Leveling). This change might add the functionality you are looking for, but if it does not, it is unlikely that I will add explicit support.

**Comment by reddvilzz** [comment]
Okay thank you for responding, I'll try the next update then I hope it can add the integration to tinker's.
